"""migration 2024-01-11_00-29-33

Revision ID: 0b2b442ed3de
Revises: b8953b35c9d8
Create Date: 2024-01-11 00:29:33.692978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2b442ed3de'
down_revision = 'b8953b35c9d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_call_results', sa.Column('tool_name', sa.String(), nullable=False))
    op.add_column('tool_call_results', sa.Column('tool_arguments', sa.String(), nullable=True))
    op.add_column('tool_call_results', sa.Column('tool_results', sa.String(), nullable=True))
    op.add_column('tool_call_results', sa.Column('record_created', sa.DateTime(), nullable=False))
    op.drop_column('tool_call_results', 'name')
    op.drop_column('tool_call_results', 'results_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_call_results', sa.Column('results_value', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tool_call_results', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tool_call_results', 'record_created')
    op.drop_column('tool_call_results', 'tool_results')
    op.drop_column('tool_call_results', 'tool_arguments')
    op.drop_column('tool_call_results', 'tool_name')
    # ### end Alembic commands ###
