"""migration 2023-08-25_12-00-56

Revision ID: 1248aa6d6b8e
Revises: 36473cc759e5
Create Date: 2023-08-25 12:00:56.534426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1248aa6d6b8e'
down_revision = '36473cc759e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
