"""migration 2023-08-29_17-18-23

Revision ID: 239fd28ffafa
Revises: 743192c911a5
Create Date: 2023-08-29 17:18:24.235285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239fd28ffafa'
down_revision = '743192c911a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'collection_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'collection_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
