"""migration 2023-12-11_09-46-03

Revision ID: 29a4bd919d3b
Revises: cb701afc2bf5
Create Date: 2023-12-11 09:46:03.809484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "29a4bd919d3b"
down_revision = "cb701afc2bf5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations", sa.Column("message_text", sa.String(), nullable=True)
    )
    # Use the Alembic connection to execute raw SQL
    conn = op.get_bind()

    # Copy data from 'conversation_text' to 'message_text'
    conn.execute(sa.text("UPDATE conversations SET message_text = conversation_text"))

    # Alter the column to be non-nullable
    op.alter_column("conversations", "message_text", nullable=False)

    op.drop_column("conversations", "conversation_text")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations",
        sa.Column(
            "conversation_text", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    
    # Use the Alembic connection to execute raw SQL
    conn = op.get_bind()

    # Copy data from 'conversation_text' to 'message_text'
    conn.execute(sa.text("UPDATE conversations SET conversation_text = message_text"))
    
    op.drop_column("conversations", "message_text")
    # ### end Alembic commands ###
