"""migration 2023-12-24_22-32-01

Revision ID: 2f060381eab6
Revises: 7fe287c268cf
Create Date: 2023-12-24 22:32:02.455660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f060381eab6'
down_revision = '7fe287c268cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_files', sa.Column('code_file_sha', sa.String(), nullable=False))
    op.drop_column('code_files', 'code_file_commit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_files', sa.Column('code_file_commit', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('code_files', 'code_file_sha')
    # ### end Alembic commands ###
