"""migration 2023-08-25_11-53-05

Revision ID: 36473cc759e5
Revises: cb2cea5b5cfe
Create Date: 2023-08-25 11:53:05.961676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36473cc759e5'
down_revision = 'cb2cea5b5cfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
