"""migration 2023-08-29_23-10-05

Revision ID: 4329e523e2cd
Revises: 239fd28ffafa
Create Date: 2023-08-29 23:10:05.564782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4329e523e2cd'
down_revision = '239fd28ffafa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_collections_collection_name_key', 'document_collections', type_='unique')
    op.create_unique_constraint(None, 'document_collections', ['interaction_id', 'collection_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_collections', type_='unique')
    op.create_unique_constraint('document_collections_collection_name_key', 'document_collections', ['collection_name'])
    # ### end Alembic commands ###
