"""migration 2023-11-02_12-42-35

Revision ID: 465bf24a43ce
Revises: f2561046d44b
Create Date: 2023-11-02 12:42:35.778661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465bf24a43ce'
down_revision = 'f2561046d44b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'embedding_model_name')
    op.drop_column('conversations', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('embedding_model_name', sa.VARCHAR(), server_default=sa.text("'text-embedding-ada-002'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
