"""migration 2023-09-27_13-40-18

Revision ID: 46c7332f958a
Revises: c86759d1b2f7
Create Date: 2023-09-27 13:40:19.504557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c7332f958a'
down_revision = 'c86759d1b2f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_text_summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'document_text_summary')
    # ### end Alembic commands ###
