"""migration 2023-10-03_08-20-08

Revision ID: 6ea61f25a130
Revises: 6ef8ffe104bd
Create Date: 2023-10-03 08:20:09.521703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea61f25a130'
down_revision = '6ef8ffe104bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_text_has_summary', sa.Boolean(), nullable=False, server_default='False'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'document_text_has_summary')
    # ### end Alembic commands ###
