"""migration 2023-10-01_21-37-53

Revision ID: 6ef8ffe104bd
Revises: 90d7101bc9e2
Create Date: 2023-10-01 21:37:54.275910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef8ffe104bd'
down_revision = '90d7101bc9e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_collections_interaction_id_collection_name_key', 'document_collections', type_='unique')
    op.create_unique_constraint(None, 'document_collections', ['collection_name'])
    op.drop_constraint('document_collections_interaction_id_fkey', 'document_collections', type_='foreignkey')
    op.drop_column('document_collections', 'interaction_id')
    op.add_column('interactions', sa.Column('last_selected_collection_id', sa.Integer(), nullable=False, server_default="-1"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'last_selected_collection_id')
    op.add_column('document_collections', sa.Column('interaction_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('document_collections_interaction_id_fkey', 'document_collections', 'interactions', ['interaction_id'], ['id'])
    op.drop_constraint(None, 'document_collections', type_='unique')
    op.create_unique_constraint('document_collections_interaction_id_collection_name_key', 'document_collections', ['interaction_id', 'collection_name'])    
    # ### end Alembic commands ###
