"""migration 2023-08-29_16-55-28

Revision ID: 743192c911a5
Revises: 9facd89acd74
Create Date: 2023-08-29 16:55:28.529408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743192c911a5'
down_revision = '9facd89acd74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'document_name')
    # ### end Alembic commands ###
