"""migration 2023-09-01_12-25-15

Revision ID: 78cc562c4e1a
Revises: d5e7fd3de403
Create Date: 2023-09-01 12:25:16.414814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78cc562c4e1a'
down_revision = 'd5e7fd3de403'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'files', ['collection_id', 'file_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'files', type_='unique')
    # ### end Alembic commands ###
