"""migration 2023-12-11_10-32-46

Revision ID: 7ce9d0e618d2
Revises: 29a4bd919d3b
Create Date: 2023-12-11 10:32:47.066791

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ce9d0e618d2'
down_revision = '29a4bd919d3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_created', sa.DateTime(), nullable=False),
    sa.Column('interaction_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_role_type_id', sa.Integer(), nullable=True),
    sa.Column('message_text', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('additional_metadata', sa.String(), nullable=True),
    sa.Column('exception', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_role_type_id'], ['conversation_role_types.id'], ),
    sa.ForeignKeyConstraint(['conversation_role_type_id'], ['conversation_role_types.id'], ),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('conversations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('record_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('interaction_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conversation_role_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('additional_metadata', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exception', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('message_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_role_type_id'], ['conversation_role_types.id'], name='conversations_conversation_role_type_id_fkey'),
    sa.ForeignKeyConstraint(['conversation_role_type_id'], ['conversation_role_types.id'], name='conversations_conversation_role_type_id_fkey1'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], name='conversations_interaction_id_fkey'),
    sa.ForeignKeyConstraint(['interaction_id'], ['interactions.id'], name='conversations_interaction_id_fkey1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='conversations_user_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='conversations_user_id_fkey1'),
    sa.PrimaryKeyConstraint('id', name='conversations_pkey')
    )
    op.drop_table('conversation_messages')
    # ### end Alembic commands ###
