"""migration 2023-12-24_17-09-08

Revision ID: 7fe287c268cf
Revises: 9bfb9398ea0e
Create Date: 2023-12-24 17:09:09.363338

"""
from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = '7fe287c268cf'
down_revision = '9bfb9398ea0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_file_id', sa.Integer(), nullable=False),
    sa.Column('description_text', sa.String(), nullable=False),
    sa.Column('description_text_embedding', pgvector.sqlalchemy.Vector(), nullable=True),
    sa.ForeignKeyConstraint(['code_file_id'], ['code_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_file_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['code_file_id'], ['code_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('code_keywords')
    op.drop_table('code_descriptions')
    # ### end Alembic commands ###
