"""migration 2023-08-02_23-38-30

Revision ID: 8976e13a07a7
Revises: ba8dd7de69b4
Create Date: 2023-08-02 23:38:30.843038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8976e13a07a7'
down_revision = 'ba8dd7de69b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('record_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('conversation_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interaction_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('additional_metadata', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='conversations_user_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='conversations_user_id_fkey1'),
    sa.PrimaryKeyConstraint('id', name='conversations_pkey')
    )
    # ### end Alembic commands ###
