"""migration 2023-09-01_12-53-19

Revision ID: 8ef66e415618
Revises: 78cc562c4e1a
Create Date: 2023-09-01 12:53:19.641566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef66e415618'
down_revision = '78cc562c4e1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file_contents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_contents', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
