"""migration 2023-09-27_15-01-29

Revision ID: 90d7101bc9e2
Revises: 46c7332f958a
Create Date: 2023-09-27 15:01:30.699144

"""
from alembic import op
import sqlalchemy as sa

import pgvector


# revision identifiers, used by Alembic.
revision = '90d7101bc9e2'
down_revision = '46c7332f958a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('document_text_summary_embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'document_text_summary_embedding')
    # ### end Alembic commands ###
