"""migration 2023-11-30_08-40-55

Revision ID: 9449a9c475e5
Revises: 0097dc08af77
Create Date: 2023-11-30 08:40:56.397422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9449a9c475e5'
down_revision = '0097dc08af77'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('question_1', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('question_2', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('question_3', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('question_4', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('question_5', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'question_5')
    op.drop_column('documents', 'question_4')
    op.drop_column('documents', 'question_3')
    op.drop_column('documents', 'question_2')
    op.drop_column('documents', 'question_1')
    # ### end Alembic commands ###
