"""migration 2023-12-25_11-23-00

Revision ID: 94a7cdc82ec6
Revises: 8ba5573d73d7
Create Date: 2023-12-25 11:23:01.115979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94a7cdc82ec6'
down_revision = '8ba5573d73d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_files', 'code_file_valid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_files', sa.Column('code_file_valid', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
