"""migration 2024-01-12_16-38-13

Revision ID: 993d15707f0f
Revises: ecd8f0e9253f
Create Date: 2024-01-12 16:38:14.411381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993d15707f0f'
down_revision = 'ecd8f0e9253f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supported_source_control_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_control_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supported_source_control_provider_id', sa.Integer(), nullable=False),
    sa.Column('source_control_provider_name', sa.String(), nullable=False),
    sa.Column('source_control_provider_url', sa.String(), nullable=False),
    sa.Column('requires_authentication', sa.Boolean(), nullable=False),
    sa.Column('source_control_access_token', sa.String(), nullable=True),
    sa.Column('last_modified', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supported_source_control_provider_id'], ['supported_source_control_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_control_provider_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_control_providers')
    op.drop_table('supported_source_control_providers')
    # ### end Alembic commands ###
