"""migration 2023-12-24_14-41-57

Revision ID: 9bfb9398ea0e
Revises: 36fc426c7c42
Create Date: 2023-12-24 14:41:58.239861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bfb9398ea0e'
down_revision = '36fc426c7c42'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_repositories', sa.Column('last_scanned', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_repositories', 'last_scanned')
    # ### end Alembic commands ###
