"""migration 2024-01-11_00-21-49

Revision ID: b8953b35c9d8
Revises: bc6ea827eeae
Create Date: 2024-01-11 00:21:49.621904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8953b35c9d8'
down_revision = 'bc6ea827eeae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool_call_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('results_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tool_call_results')
    # ### end Alembic commands ###
