"""migration 2024-01-04_09-47-30

Revision ID: bc6ea827eeae
Revises: 32b1401cf77f
Create Date: 2024-01-04 09:47:31.193365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6ea827eeae'
down_revision = '32b1401cf77f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('document_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'document_count')
    # ### end Alembic commands ###
