"""migration 2024-02-01_13-56-34

Revision ID: be5387917d20
Revises: 75da1d37b18b
Create Date: 2024-02-01 13:56:35.114501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5387917d20'
down_revision = '75da1d37b18b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
