"""migration 2023-08-25_16-06-25

Revision ID: c0712d4516f4
Revises: ce4233932882
Create Date: 2023-08-25 16:06:25.368914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0712d4516f4'
down_revision = 'ce4233932882'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactions', sa.Column('needs_summary', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interactions', 'needs_summary')
    # ### end Alembic commands ###
