"""migration 2023-09-20_07-27-19

Revision ID: c86759d1b2f7
Revises: 2c0e187fa43b
Create Date: 2023-09-20 07:27:20.489430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86759d1b2f7'
down_revision = '2c0e187fa43b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('components', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'components', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'components', type_='foreignkey')
    op.drop_column('components', 'project_id')
    # ### end Alembic commands ###
