"""migration 2023-12-11_09-35-46

Revision ID: cb701afc2bf5
Revises: e8d072dd2a60
Create Date: 2023-12-11 09:35:47.004688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cb701afc2bf5'
down_revision = 'e8d072dd2a60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('component_dependencies')    
    op.drop_table('additional_design_inputs')
    op.drop_table('component_data_handling')
    op.drop_table('component_interactions')
    op.drop_table('components')    
    op.drop_table('design_decisions')
    op.drop_table('requirements')
    op.drop_table('user_needs')
    op.drop_table('projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirements',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('requirements_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_need_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='requirements_project_id_fkey'),
    sa.ForeignKeyConstraint(['user_need_id'], ['user_needs.id'], name='requirements_user_need_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='requirements_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('design_decisions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('decision', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('details', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('component', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='design_decisions_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='design_decisions_pkey')
    )
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('projects_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('record_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='projects_pkey'),
    sa.UniqueConstraint('project_name', name='projects_project_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('component_data_handling',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('component_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='component_data_handling_component_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='component_data_handling_pkey')
    )
    op.create_table('additional_design_inputs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requirement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name='additional_design_inputs_file_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='additional_design_inputs_project_id_fkey'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name='additional_design_inputs_requirement_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='additional_design_inputs_pkey')
    )
    op.create_table('component_interactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('component_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interacts_with', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='component_interactions_component_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='component_interactions_pkey')
    )
    op.create_table('components',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('components_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('purpose', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='components_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='components_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_needs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='user_needs_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_needs_pkey')
    )
    op.create_table('component_dependencies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('component_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dependency_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='component_dependencies_component_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='component_dependencies_pkey')
    )
    # ### end Alembic commands ###
