"""migration 2023-09-19_12-42-43

Revision ID: cbe7f771d58b
Revises: dea969228b32
Create Date: 2023-09-19 12:42:44.275103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe7f771d58b'
down_revision = 'dea969228b32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_decisions', sa.Column('component', sa.String(), nullable=True))
    op.drop_column('design_decisions', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('design_decisions', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('design_decisions', 'component')
    # ### end Alembic commands ###
