"""migration 2023-08-25_12-05-02

Revision ID: ce4233932882
Revises: 1248aa6d6b8e
Create Date: 2023-08-25 12:05:03.274785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce4233932882'
down_revision = '1248aa6d6b8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'conversations', 'interactions', ['interaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    # ### end Alembic commands ###
