"""migration 2024-02-10_14-46-28

Revision ID: d8992a7d7e6a
Revises: 242bd425a76c
Create Date: 2024-02-10 14:46:28.827727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8992a7d7e6a'
down_revision = '242bd425a76c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the collection_type to embedding_name, keeping the data
    op.add_column('document_collections', sa.Column('embedding_name', sa.String(), nullable=True))
    op.execute("UPDATE document_collections SET embedding_name = collection_type")
    op.drop_column('document_collections', 'collection_type')
    op.alter_column('document_collections', 'embedding_name', nullable=False)    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_collections', sa.Column('collection_type', sa.String(), nullable=True))
    op.execute("UPDATE document_collections SET collection_type = embedding_name")
    op.drop_column('document_collections', 'embedding_name')
    op.alter_column('document_collections', 'collection_type', nullable=False)
    # ### end Alembic commands ###
