"""migration 2023-09-01_12-59-12

Revision ID: dc9bf5845938
Revises: 8ef66e415618
Create Date: 2023-09-01 12:59:12.703525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9bf5845938'
down_revision = '8ef66e415618'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_classification', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file_classification')
    # ### end Alembic commands ###
