"""migration 2023-09-18_10-19-59

Revision ID: dea969228b32
Revises: febe4efefe7a
Create Date: 2023-09-18 10:19:59.771916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea969228b32'
down_revision = 'febe4efefe7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
