"""migration 2023-09-16_10-30-58

Revision ID: ea187f42471e
Revises: a11f4098f72e
Create Date: 2023-09-16 10:30:58.994085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea187f42471e'
down_revision = 'a11f4098f72e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('file_hash', sa.String(), nullable=False))
    op.add_column('files', sa.Column('file_data', sa.LargeBinary(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'file_data')
    op.drop_column('files', 'file_hash')
    # ### end Alembic commands ###
