"""migration 2024-01-11_19-27-40

Revision ID: ecd8f0e9253f
Revises: 0b2b442ed3de
Create Date: 2024-01-11 19:27:40.619269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecd8f0e9253f'
down_revision = '0b2b442ed3de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
