"""migration 2023-11-02_10-47-04

Revision ID: f2561046d44b
Revises: 6ea61f25a130
Create Date: 2023-11-02 10:47:05.154461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2561046d44b'
down_revision = '6ea61f25a130'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('embedding_model_name', sa.String(), nullable=False, server_default="text-embedding-ada-002"))    
    op.add_column('documents', sa.Column('embedding_model_name', sa.String(), nullable=False, server_default="text-embedding-ada-002"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'embedding_model_name')
    op.drop_column('conversations', 'embedding_model_name')
    # ### end Alembic commands ###
