"""migration 2024-01-04_08-09-31

Revision ID: 32b1401cf77f
Revises: 9a7e026f2eb5
Create Date: 2024-01-04 08:09:33.079160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b1401cf77f'
down_revision = '9a7e026f2eb5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('chunk_size', sa.Integer(), nullable=False, server_default='500'))
    op.add_column('files', sa.Column('chunk_overlap', sa.Integer(), nullable=False, server_default='50'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'chunk_overlap')
    op.drop_column('files', 'chunk_size')
    # ### end Alembic commands ###
