"""migration 2024-01-22_15-25-16

Revision ID: 4a6da61416a8
Revises: 993d15707f0f
Create Date: 2024-01-22 15:25:17.412895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6da61416a8'
down_revision = '993d15707f0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool_call_results', sa.Column('include_in_conversation', sa.Boolean(), nullable=False, server_default='False'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tool_call_results', 'include_in_conversation')
    # ### end Alembic commands ###
