"""migration 2024-02-04_10-09-54

Revision ID: 4aec00e27b34
Revises: be5387917d20
Create Date: 2024-02-04 10:09:54.827373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aec00e27b34'
down_revision = 'be5387917d20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('available_for_llm', sa.Boolean(), nullable=False, server_default='False'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'available_for_llm')
    # ### end Alembic commands ###
