"""migration 2024-03-17_12-49-52

Revision ID: 2d70263d97e2
Revises: c3a59416441c
Create Date: 2024-03-17 12:49:52.880481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d70263d97e2'
down_revision = 'c3a59416441c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Set the server default to False
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='False'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
