"""migration 2024-03-13_11-18-58

Revision ID: 46a0d8482420
Revises: ec8f10d5a2f7
Create Date: 2024-03-13 11:18:58.817340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46a0d8482420'
down_revision = 'ec8f10d5a2f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('session_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'session_created')
    op.drop_column('users', 'session_id')
    # ### end Alembic commands ###
