"""migration 2024-03-22_12-53-16

Revision ID: 87ba18a8955c
Revises: 0fcbf82a80f9
Create Date: 2024-03-22 12:53:16.939308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87ba18a8955c'
down_revision = '0fcbf82a80f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('source_control_providers_source_control_provider_name_key', 'source_control_providers', type_='unique')
    op.add_column('source_control_providers', sa.Column('user_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key(None, 'source_control_providers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'source_control_providers', type_='foreignkey')
    op.drop_column('source_control_providers', 'user_id')
    op.create_unique_constraint('source_control_providers_source_control_provider_name_key', 'source_control_providers', ['source_control_provider_name'])
    # ### end Alembic commands ###
