"""migration 2024-03-15_14-20-17

Revision ID: c3a59416441c
Revises: 46a0d8482420
Create Date: 2024-03-15 14:20:18.053890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a59416441c'
down_revision = '46a0d8482420'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_task_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('current_state', sa.String(), nullable=False),
    sa.Column('associated_user_id', sa.Integer(), nullable=True),
    sa.Column('record_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['associated_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_task_id')
    )
    op.create_table('task_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('record_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_history')
    op.drop_table('tasks')
    # ### end Alembic commands ###
