"""migration 2024-03-17_14-15-12

Revision ID: e5d3eb330b02
Revises: f7a2bd4ea8a2
Create Date: 2024-03-17 14:15:13.028908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d3eb330b02'
down_revision = 'f7a2bd4ea8a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_collections', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document_collections', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_collections', type_='foreignkey')
    op.drop_column('document_collections', 'user_id')
    # ### end Alembic commands ###
