"""migration 2024-03-17_13-02-34

Revision ID: f7a2bd4ea8a2
Revises: 2d70263d97e2
Create Date: 2024-03-17 13:02:34.979200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a2bd4ea8a2'
down_revision = '2d70263d97e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('enabled', sa.Boolean(), nullable=False, server_default='True'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'enabled')
    # ### end Alembic commands ###
